// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: option_example.proto
// Protobuf Java Version: 4.27.0

package com.example.options;

public final class OptionExample {
  private OptionExample() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      OptionExample.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_OptionMessageTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_OptionMessageTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_OptionMessageOther_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_OptionMessageOther_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024option_example.proto\022\007example\"U\n\021Optio" +
      "nMessageTest\022\n\n\002id\030\001 \001(\005\022\021\n\tis_simple\030\002 " +
      "\001(\010\022\014\n\004name\030\003 \001(\t\022\023\n\013sample_list\030\004 \003(\005\"#" +
      "\n\022OptionMessageOther\022\r\n\005hello\030\001 \001(\tB\027\n\023c" +
      "om.example.optionsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_OptionMessageTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_OptionMessageTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_OptionMessageTest_descriptor,
        new java.lang.String[] { "Id", "IsSimple", "Name", "SampleList", });
    internal_static_example_OptionMessageOther_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_OptionMessageOther_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_OptionMessageOther_descriptor,
        new java.lang.String[] { "Hello", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
