// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: option_example.proto
// Protobuf Java Version: 4.27.0

package com.example.options;

public interface OptionMessageOtherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.OptionMessageOther)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hello = 1;</code>
   * @return The hello.
   */
  java.lang.String getHello();
  /**
   * <code>string hello = 1;</code>
   * @return The bytes for hello.
   */
  com.google.protobuf.ByteString
      getHelloBytes();
}
