// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: complex.proto
// Protobuf Java Version: 4.27.0

package example;

public final class Complex {
  private Complex() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Complex.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.ComplexMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     * @return Whether the oneDummy field is set.
     */
    boolean hasOneDummy();
    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     * @return The oneDummy.
     */
    example.Complex.DummyMessage getOneDummy();
    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     */
    example.Complex.DummyMessageOrBuilder getOneDummyOrBuilder();

    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    java.util.List<example.Complex.DummyMessage> 
        getMultipleDummyList();
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    example.Complex.DummyMessage getMultipleDummy(int index);
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    int getMultipleDummyCount();
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    java.util.List<? extends example.Complex.DummyMessageOrBuilder> 
        getMultipleDummyOrBuilderList();
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    example.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code example.ComplexMessage}
   */
  public static final class ComplexMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.ComplexMessage)
      ComplexMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        ComplexMessage.class.getName());
    }
    // Use ComplexMessage.newBuilder() to construct.
    private ComplexMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ComplexMessage() {
      multipleDummy_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.Complex.internal_static_example_ComplexMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.Complex.internal_static_example_ComplexMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.Complex.ComplexMessage.class, example.Complex.ComplexMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ONE_DUMMY_FIELD_NUMBER = 2;
    private example.Complex.DummyMessage oneDummy_;
    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     * @return Whether the oneDummy field is set.
     */
    @java.lang.Override
    public boolean hasOneDummy() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     * @return The oneDummy.
     */
    @java.lang.Override
    public example.Complex.DummyMessage getOneDummy() {
      return oneDummy_ == null ? example.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
    }
    /**
     * <code>.example.DummyMessage one_dummy = 2;</code>
     */
    @java.lang.Override
    public example.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
      return oneDummy_ == null ? example.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
    }

    public static final int MULTIPLE_DUMMY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<example.Complex.DummyMessage> multipleDummy_;
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    @java.lang.Override
    public java.util.List<example.Complex.DummyMessage> getMultipleDummyList() {
      return multipleDummy_;
    }
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends example.Complex.DummyMessageOrBuilder> 
        getMultipleDummyOrBuilderList() {
      return multipleDummy_;
    }
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    @java.lang.Override
    public int getMultipleDummyCount() {
      return multipleDummy_.size();
    }
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    @java.lang.Override
    public example.Complex.DummyMessage getMultipleDummy(int index) {
      return multipleDummy_.get(index);
    }
    /**
     * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
     */
    @java.lang.Override
    public example.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
        int index) {
      return multipleDummy_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getOneDummy());
      }
      for (int i = 0; i < multipleDummy_.size(); i++) {
        output.writeMessage(3, multipleDummy_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOneDummy());
      }
      for (int i = 0; i < multipleDummy_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, multipleDummy_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.Complex.ComplexMessage)) {
        return super.equals(obj);
      }
      example.Complex.ComplexMessage other = (example.Complex.ComplexMessage) obj;

      if (hasOneDummy() != other.hasOneDummy()) return false;
      if (hasOneDummy()) {
        if (!getOneDummy()
            .equals(other.getOneDummy())) return false;
      }
      if (!getMultipleDummyList()
          .equals(other.getMultipleDummyList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOneDummy()) {
        hash = (37 * hash) + ONE_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getOneDummy().hashCode();
      }
      if (getMultipleDummyCount() > 0) {
        hash = (37 * hash) + MULTIPLE_DUMMY_FIELD_NUMBER;
        hash = (53 * hash) + getMultipleDummyList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.Complex.ComplexMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.ComplexMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.ComplexMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.ComplexMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.ComplexMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.ComplexMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.Complex.ComplexMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static example.Complex.ComplexMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static example.Complex.ComplexMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.Complex.ComplexMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.Complex.ComplexMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.ComplexMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.ComplexMessage)
        example.Complex.ComplexMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.Complex.internal_static_example_ComplexMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.Complex.internal_static_example_ComplexMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.Complex.ComplexMessage.class, example.Complex.ComplexMessage.Builder.class);
      }

      // Construct using example.Complex.ComplexMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getOneDummyFieldBuilder();
          getMultipleDummyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        oneDummy_ = null;
        if (oneDummyBuilder_ != null) {
          oneDummyBuilder_.dispose();
          oneDummyBuilder_ = null;
        }
        if (multipleDummyBuilder_ == null) {
          multipleDummy_ = java.util.Collections.emptyList();
        } else {
          multipleDummy_ = null;
          multipleDummyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.Complex.internal_static_example_ComplexMessage_descriptor;
      }

      @java.lang.Override
      public example.Complex.ComplexMessage getDefaultInstanceForType() {
        return example.Complex.ComplexMessage.getDefaultInstance();
      }

      @java.lang.Override
      public example.Complex.ComplexMessage build() {
        example.Complex.ComplexMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.Complex.ComplexMessage buildPartial() {
        example.Complex.ComplexMessage result = new example.Complex.ComplexMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(example.Complex.ComplexMessage result) {
        if (multipleDummyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            multipleDummy_ = java.util.Collections.unmodifiableList(multipleDummy_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.multipleDummy_ = multipleDummy_;
        } else {
          result.multipleDummy_ = multipleDummyBuilder_.build();
        }
      }

      private void buildPartial0(example.Complex.ComplexMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.oneDummy_ = oneDummyBuilder_ == null
              ? oneDummy_
              : oneDummyBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.Complex.ComplexMessage) {
          return mergeFrom((example.Complex.ComplexMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.Complex.ComplexMessage other) {
        if (other == example.Complex.ComplexMessage.getDefaultInstance()) return this;
        if (other.hasOneDummy()) {
          mergeOneDummy(other.getOneDummy());
        }
        if (multipleDummyBuilder_ == null) {
          if (!other.multipleDummy_.isEmpty()) {
            if (multipleDummy_.isEmpty()) {
              multipleDummy_ = other.multipleDummy_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMultipleDummyIsMutable();
              multipleDummy_.addAll(other.multipleDummy_);
            }
            onChanged();
          }
        } else {
          if (!other.multipleDummy_.isEmpty()) {
            if (multipleDummyBuilder_.isEmpty()) {
              multipleDummyBuilder_.dispose();
              multipleDummyBuilder_ = null;
              multipleDummy_ = other.multipleDummy_;
              bitField0_ = (bitField0_ & ~0x00000002);
              multipleDummyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMultipleDummyFieldBuilder() : null;
            } else {
              multipleDummyBuilder_.addAllMessages(other.multipleDummy_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                input.readMessage(
                    getOneDummyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                example.Complex.DummyMessage m =
                    input.readMessage(
                        example.Complex.DummyMessage.parser(),
                        extensionRegistry);
                if (multipleDummyBuilder_ == null) {
                  ensureMultipleDummyIsMutable();
                  multipleDummy_.add(m);
                } else {
                  multipleDummyBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private example.Complex.DummyMessage oneDummy_;
      private com.google.protobuf.SingleFieldBuilder<
          example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder> oneDummyBuilder_;
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       * @return Whether the oneDummy field is set.
       */
      public boolean hasOneDummy() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       * @return The oneDummy.
       */
      public example.Complex.DummyMessage getOneDummy() {
        if (oneDummyBuilder_ == null) {
          return oneDummy_ == null ? example.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        } else {
          return oneDummyBuilder_.getMessage();
        }
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(example.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oneDummy_ = value;
        } else {
          oneDummyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public Builder setOneDummy(
          example.Complex.DummyMessage.Builder builderForValue) {
        if (oneDummyBuilder_ == null) {
          oneDummy_ = builderForValue.build();
        } else {
          oneDummyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public Builder mergeOneDummy(example.Complex.DummyMessage value) {
        if (oneDummyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            oneDummy_ != null &&
            oneDummy_ != example.Complex.DummyMessage.getDefaultInstance()) {
            getOneDummyBuilder().mergeFrom(value);
          } else {
            oneDummy_ = value;
          }
        } else {
          oneDummyBuilder_.mergeFrom(value);
        }
        if (oneDummy_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public Builder clearOneDummy() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oneDummy_ = null;
        if (oneDummyBuilder_ != null) {
          oneDummyBuilder_.dispose();
          oneDummyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public example.Complex.DummyMessage.Builder getOneDummyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOneDummyFieldBuilder().getBuilder();
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      public example.Complex.DummyMessageOrBuilder getOneDummyOrBuilder() {
        if (oneDummyBuilder_ != null) {
          return oneDummyBuilder_.getMessageOrBuilder();
        } else {
          return oneDummy_ == null ?
              example.Complex.DummyMessage.getDefaultInstance() : oneDummy_;
        }
      }
      /**
       * <code>.example.DummyMessage one_dummy = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder> 
          getOneDummyFieldBuilder() {
        if (oneDummyBuilder_ == null) {
          oneDummyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder>(
                  getOneDummy(),
                  getParentForChildren(),
                  isClean());
          oneDummy_ = null;
        }
        return oneDummyBuilder_;
      }

      private java.util.List<example.Complex.DummyMessage> multipleDummy_ =
        java.util.Collections.emptyList();
      private void ensureMultipleDummyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          multipleDummy_ = new java.util.ArrayList<example.Complex.DummyMessage>(multipleDummy_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder> multipleDummyBuilder_;

      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<example.Complex.DummyMessage> getMultipleDummyList() {
        if (multipleDummyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(multipleDummy_);
        } else {
          return multipleDummyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public int getMultipleDummyCount() {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.size();
        } else {
          return multipleDummyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public example.Complex.DummyMessage getMultipleDummy(int index) {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.get(index);
        } else {
          return multipleDummyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder setMultipleDummy(
          int index, example.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.set(index, value);
          onChanged();
        } else {
          multipleDummyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder setMultipleDummy(
          int index, example.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.set(index, builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(example.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(value);
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          int index, example.Complex.DummyMessage value) {
        if (multipleDummyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(index, value);
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          example.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addMultipleDummy(
          int index, example.Complex.DummyMessage.Builder builderForValue) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.add(index, builderForValue.build());
          onChanged();
        } else {
          multipleDummyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder addAllMultipleDummy(
          java.lang.Iterable<? extends example.Complex.DummyMessage> values) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, multipleDummy_);
          onChanged();
        } else {
          multipleDummyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder clearMultipleDummy() {
        if (multipleDummyBuilder_ == null) {
          multipleDummy_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          multipleDummyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public Builder removeMultipleDummy(int index) {
        if (multipleDummyBuilder_ == null) {
          ensureMultipleDummyIsMutable();
          multipleDummy_.remove(index);
          onChanged();
        } else {
          multipleDummyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public example.Complex.DummyMessage.Builder getMultipleDummyBuilder(
          int index) {
        return getMultipleDummyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public example.Complex.DummyMessageOrBuilder getMultipleDummyOrBuilder(
          int index) {
        if (multipleDummyBuilder_ == null) {
          return multipleDummy_.get(index);  } else {
          return multipleDummyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<? extends example.Complex.DummyMessageOrBuilder> 
           getMultipleDummyOrBuilderList() {
        if (multipleDummyBuilder_ != null) {
          return multipleDummyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(multipleDummy_);
        }
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public example.Complex.DummyMessage.Builder addMultipleDummyBuilder() {
        return getMultipleDummyFieldBuilder().addBuilder(
            example.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public example.Complex.DummyMessage.Builder addMultipleDummyBuilder(
          int index) {
        return getMultipleDummyFieldBuilder().addBuilder(
            index, example.Complex.DummyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .example.DummyMessage multiple_dummy = 3;</code>
       */
      public java.util.List<example.Complex.DummyMessage.Builder> 
           getMultipleDummyBuilderList() {
        return getMultipleDummyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder> 
          getMultipleDummyFieldBuilder() {
        if (multipleDummyBuilder_ == null) {
          multipleDummyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              example.Complex.DummyMessage, example.Complex.DummyMessage.Builder, example.Complex.DummyMessageOrBuilder>(
                  multipleDummy_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          multipleDummy_ = null;
        }
        return multipleDummyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:example.ComplexMessage)
    }

    // @@protoc_insertion_point(class_scope:example.ComplexMessage)
    private static final example.Complex.ComplexMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.Complex.ComplexMessage();
    }

    public static example.Complex.ComplexMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexMessage>
        PARSER = new com.google.protobuf.AbstractParser<ComplexMessage>() {
      @java.lang.Override
      public ComplexMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComplexMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.Complex.ComplexMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DummyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.DummyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code example.DummyMessage}
   */
  public static final class DummyMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.DummyMessage)
      DummyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        DummyMessage.class.getName());
    }
    // Use DummyMessage.newBuilder() to construct.
    private DummyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DummyMessage() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.Complex.internal_static_example_DummyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.Complex.internal_static_example_DummyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.Complex.DummyMessage.class, example.Complex.DummyMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.Complex.DummyMessage)) {
        return super.equals(obj);
      }
      example.Complex.DummyMessage other = (example.Complex.DummyMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.Complex.DummyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.DummyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.DummyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.DummyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.Complex.DummyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.Complex.DummyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.Complex.DummyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static example.Complex.DummyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static example.Complex.DummyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.Complex.DummyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.Complex.DummyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.DummyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.DummyMessage)
        example.Complex.DummyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.Complex.internal_static_example_DummyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.Complex.internal_static_example_DummyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.Complex.DummyMessage.class, example.Complex.DummyMessage.Builder.class);
      }

      // Construct using example.Complex.DummyMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.Complex.internal_static_example_DummyMessage_descriptor;
      }

      @java.lang.Override
      public example.Complex.DummyMessage getDefaultInstanceForType() {
        return example.Complex.DummyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public example.Complex.DummyMessage build() {
        example.Complex.DummyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.Complex.DummyMessage buildPartial() {
        example.Complex.DummyMessage result = new example.Complex.DummyMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(example.Complex.DummyMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.Complex.DummyMessage) {
          return mergeFrom((example.Complex.DummyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.Complex.DummyMessage other) {
        if (other == example.Complex.DummyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.DummyMessage)
    }

    // @@protoc_insertion_point(class_scope:example.DummyMessage)
    private static final example.Complex.DummyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.Complex.DummyMessage();
    }

    public static example.Complex.DummyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DummyMessage>
        PARSER = new com.google.protobuf.AbstractParser<DummyMessage>() {
      @java.lang.Override
      public DummyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DummyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DummyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.Complex.DummyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_ComplexMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_ComplexMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_DummyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_DummyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomplex.proto\022\007example\"i\n\016ComplexMessa" +
      "ge\022(\n\tone_dummy\030\002 \001(\0132\025.example.DummyMes" +
      "sage\022-\n\016multiple_dummy\030\003 \003(\0132\025.example.D" +
      "ummyMessage\"(\n\014DummyMessage\022\n\n\002id\030\001 \001(\005\022" +
      "\014\n\004name\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_ComplexMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_ComplexMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_ComplexMessage_descriptor,
        new java.lang.String[] { "OneDummy", "MultipleDummy", });
    internal_static_example_DummyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_DummyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_DummyMessage_descriptor,
        new java.lang.String[] { "Id", "Name", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
