// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enum_example.proto
// Protobuf Java Version: 4.27.0

package example;

public final class EnumExample {
  private EnumExample() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      EnumExample.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code example.DayOfTheWeek}
   */
  public enum DayOfTheWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURSDAY = 4;</code>
     */
    THURSDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    /**
     * <code>SUNDAY = 7;</code>
     */
    SUNDAY(7),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        DayOfTheWeek.class.getName());
    }
    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURSDAY = 4;</code>
     */
    public static final int THURSDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;
    /**
     * <code>SUNDAY = 7;</code>
     */
    public static final int SUNDAY_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfTheWeek valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DayOfTheWeek forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURSDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        case 7: return SUNDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfTheWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>() {
            public DayOfTheWeek findValueByNumber(int number) {
              return DayOfTheWeek.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return example.EnumExample.getDescriptor().getEnumTypes().get(0);
    }

    private static final DayOfTheWeek[] VALUES = values();

    public static DayOfTheWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DayOfTheWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:example.DayOfTheWeek)
  }

  public interface EnumMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.EnumMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The enum numeric value on the wire for dayOfTheWeek.
     */
    int getDayOfTheWeekValue();
    /**
     * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The dayOfTheWeek.
     */
    example.EnumExample.DayOfTheWeek getDayOfTheWeek();
  }
  /**
   * Protobuf type {@code example.EnumMessage}
   */
  public static final class EnumMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.EnumMessage)
      EnumMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        EnumMessage.class.getName());
    }
    // Use EnumMessage.newBuilder() to construct.
    private EnumMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EnumMessage() {
      dayOfTheWeek_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.EnumExample.internal_static_example_EnumMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.EnumExample.internal_static_example_EnumMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.EnumExample.EnumMessage.class, example.EnumExample.EnumMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int DAY_OF_THE_WEEK_FIELD_NUMBER = 2;
    private int dayOfTheWeek_ = 0;
    /**
     * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The enum numeric value on the wire for dayOfTheWeek.
     */
    @java.lang.Override public int getDayOfTheWeekValue() {
      return dayOfTheWeek_;
    }
    /**
     * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The dayOfTheWeek.
     */
    @java.lang.Override public example.EnumExample.DayOfTheWeek getDayOfTheWeek() {
      example.EnumExample.DayOfTheWeek result = example.EnumExample.DayOfTheWeek.forNumber(dayOfTheWeek_);
      return result == null ? example.EnumExample.DayOfTheWeek.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (dayOfTheWeek_ != example.EnumExample.DayOfTheWeek.UNKNOWN.getNumber()) {
        output.writeEnum(2, dayOfTheWeek_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (dayOfTheWeek_ != example.EnumExample.DayOfTheWeek.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dayOfTheWeek_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.EnumExample.EnumMessage)) {
        return super.equals(obj);
      }
      example.EnumExample.EnumMessage other = (example.EnumExample.EnumMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (dayOfTheWeek_ != other.dayOfTheWeek_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DAY_OF_THE_WEEK_FIELD_NUMBER;
      hash = (53 * hash) + dayOfTheWeek_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.EnumExample.EnumMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.EnumExample.EnumMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static example.EnumExample.EnumMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static example.EnumExample.EnumMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static example.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.EnumExample.EnumMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.EnumMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.EnumMessage)
        example.EnumExample.EnumMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.EnumExample.internal_static_example_EnumMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.EnumExample.internal_static_example_EnumMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.EnumExample.EnumMessage.class, example.EnumExample.EnumMessage.Builder.class);
      }

      // Construct using example.EnumExample.EnumMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        dayOfTheWeek_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.EnumExample.internal_static_example_EnumMessage_descriptor;
      }

      @java.lang.Override
      public example.EnumExample.EnumMessage getDefaultInstanceForType() {
        return example.EnumExample.EnumMessage.getDefaultInstance();
      }

      @java.lang.Override
      public example.EnumExample.EnumMessage build() {
        example.EnumExample.EnumMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.EnumExample.EnumMessage buildPartial() {
        example.EnumExample.EnumMessage result = new example.EnumExample.EnumMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(example.EnumExample.EnumMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dayOfTheWeek_ = dayOfTheWeek_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.EnumExample.EnumMessage) {
          return mergeFrom((example.EnumExample.EnumMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.EnumExample.EnumMessage other) {
        if (other == example.EnumExample.EnumMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.dayOfTheWeek_ != 0) {
          setDayOfTheWeekValue(other.getDayOfTheWeekValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                dayOfTheWeek_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int dayOfTheWeek_ = 0;
      /**
       * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
       * @return The enum numeric value on the wire for dayOfTheWeek.
       */
      @java.lang.Override public int getDayOfTheWeekValue() {
        return dayOfTheWeek_;
      }
      /**
       * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
       * @param value The enum numeric value on the wire for dayOfTheWeek to set.
       * @return This builder for chaining.
       */
      public Builder setDayOfTheWeekValue(int value) {
        dayOfTheWeek_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
       * @return The dayOfTheWeek.
       */
      @java.lang.Override
      public example.EnumExample.DayOfTheWeek getDayOfTheWeek() {
        example.EnumExample.DayOfTheWeek result = example.EnumExample.DayOfTheWeek.forNumber(dayOfTheWeek_);
        return result == null ? example.EnumExample.DayOfTheWeek.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
       * @param value The dayOfTheWeek to set.
       * @return This builder for chaining.
       */
      public Builder setDayOfTheWeek(example.EnumExample.DayOfTheWeek value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        dayOfTheWeek_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.DayOfTheWeek day_of_the_week = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDayOfTheWeek() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dayOfTheWeek_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.EnumMessage)
    }

    // @@protoc_insertion_point(class_scope:example.EnumMessage)
    private static final example.EnumExample.EnumMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.EnumExample.EnumMessage();
    }

    public static example.EnumExample.EnumMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnumMessage>
        PARSER = new com.google.protobuf.AbstractParser<EnumMessage>() {
      @java.lang.Override
      public EnumMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EnumMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnumMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.EnumExample.EnumMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_EnumMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_EnumMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022enum_example.proto\022\007example\"I\n\013EnumMes" +
      "sage\022\n\n\002id\030\001 \001(\005\022.\n\017day_of_the_week\030\002 \001(" +
      "\0162\025.example.DayOfTheWeek*w\n\014DayOfTheWeek" +
      "\022\013\n\007UNKNOWN\020\000\022\n\n\006MONDAY\020\001\022\013\n\007TUESDAY\020\002\022\r" +
      "\n\tWEDNESDAY\020\003\022\014\n\010THURSDAY\020\004\022\n\n\006FRIDAY\020\005\022" +
      "\014\n\010SATURDAY\020\006\022\n\n\006SUNDAY\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_EnumMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_EnumMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_EnumMessage_descriptor,
        new java.lang.String[] { "Id", "DayOfTheWeek", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
